### ISSUE TITLE
Setting prefetch size

### ISSUE THREAD

**Issue by blewa** [reidmorrison/jruby-jms#20]
Hi,
Do you know what the default prefetch size is set to for clients?  Is there a way to go about setting it that I'm just missing?

Thanks!

**Comment by blewa** [comment]
Nevermind, answered my own question here.  Appending `?jms.prefetchPolicy.all=10` to the connection URL will set the prefetch to 10.

**Comment by reidmorrison** [comment]
Excellent, glad you were able to find the relevant option.
